apiVersion: apps/v1
kind: Deployment
metadata:
  name: go8s-d
  labels:
    app: go8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go8s
  template:
    metadata:
      labels:
        app: go8s
    spec:
      containers:
        - name: go8s
          image: go8s
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "32Mi"
            limits:
              cpu: "300m"
              memory: "64Mi"
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: go8s-np
spec:
  type: NodePort
  selector:
    app: go8s
  ports:
    - port: 8000
      targetPort: 8000
