apiVersion: apps/v1
kind: Deployment
metadata:
  name: node8s-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: node8s
  template:
    metadata:
      labels:
        app: node8s
    spec:
      containers:
        - name: node8s
          image: node8s
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "250m"
              memory: "32Mi"
            limits:
              cpu: "300m"
              memory: "64Mi"
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: node8s-nodeport

spec:
  type: NodePort
  selector:
    app: node8s
  ports:
    - port: 3000
      targetPort: 3000
