apiVersion: apps/v1
kind: Deployment
metadata:
  name: py8s-d
  labels:
    app: py8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: py8s
  template:
    metadata:
      labels:
        app: py8s
    spec:
      containers:
        - name: py8s
          image: py8s
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"
              memory: "32Mi"
            limits:
              cpu: "300m"
              memory: "64Mi"
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: py8s-np
spec:
  type: NodePort
  selector:
    app: py8s
  ports:
    - port: 5000
      targetPort: 5000
